name: Bug Report
description: "Create a report to help us improve."
title: "[BUG]"

body: 
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Attach screenshots if useful.
    validations:
      required: true

  - type: input
    attributes:
      label: Mosaic version
      description: Output of `mosaic --version`
      placeholder: "Example: 1.4.0"
    validations:
      required: true
   
  - type: dropdown
    attributes:
      label: Device
      options:
        - Linux Desktop
        - Linux Smartphone
        - Halium Smartphone
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System
      placeholder: "Example: Ubuntu 20.04 amd64"
    validations:
      required: true

  - type: input
    attributes:
      label: Kernel version
      description: Output of `uname --kernel-release`
      placeholder: "Example: 5.19.0-38-generic"
    validations:
      required: true

  - type: input
    attributes:
      label: Desktop Environment
      placeholder: "Example: GNOME 40"
    validations:
      required: true

  - type: input
    attributes:
      label: GPU
      placeholder: "Example: AMD Radeon™ RX 5700"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Logs"
      description: |
        Run `mosaic bugreport` to generate an archive of log-files, and attach it here.
        If unavailable, manually attach the files listed below instead
      value: |
        /var/lib/mosaic/mosaic.cfg
        /var/lib/mosaic/mosaic.prop
        /var/lib/mosaic/mosaic_base.prop
        /var/lib/mosaic/mosaic.log
        `sudo mosaic shell -- logcat -d | tee logcat.txt`
        `sudo dmesg | tee dmesg.txt`
    validations:
      required: true
