/* A launcher that runs any class with the framework's JNI natives registered.
 *
 * Why this exists. dalvikvm runs an arbitrary class from an arbitrary class path
 * but never registers the framework's natives, so android.os.Binder and friends
 * are "No implementation found". app_process does register them, through
 * AndroidRuntime::start -> startReg, but startReg is not exported and
 * app_process is not a general launcher.
 *
 * The registrars startReg calls, however, *are* exported: libandroid_runtime.so
 * exports 152 symbols named register_*. This does what startReg does — calls each
 * of them with a JNIEnv — and then runs the class, which is the piece both
 * dalvikvm and app_process are missing for this purpose.
 *
 * It is a shared object rather than an executable because building a Bionic
 * executable needs the Android crt objects, which the image does not ship. It is
 * preloaded into a Bionic binary that creates a VM -- dalvikvm will do -- and it
 * interposes JNI_CreateJavaVM, so the work happens when the host's main asks for
 * the VM and the launcher exits before the host's own body runs. A constructor
 * would be too early: libc has not set up environ at that point, so the
 * environment is unreadable.
 *
 * Configuration comes from the environment, because a constructor has no argv:
 *
 *   MOSAIC_LAUNCH_CLASS      main class to run
 *   MOSAIC_LAUNCH_RUNTIME    path to libandroid_runtime.so
 *   MOSAIC_LAUNCH_ARGS       optional, space separated
 *
 * The class path and boot class path come from the host's own arguments, so the
 * invocation is an ordinary dalvikvm one; only the class to run is ours.
 *
 * The JNI function table is indexed directly rather than declared in full. The
 * indices used are from the JNI specification and are fixed for the ABI:
 * FindClass (6) and GetStaticMethodID (113) in the call interface, and the array
 * and string helpers from the standard order.
 */

typedef unsigned char jboolean;
typedef int jint;
typedef void *jobject;
typedef void *jclass;
typedef void *jmethodID;
typedef void *jstring;
typedef void *jobjectArray;
typedef void *JavaVM;
typedef void *JNIEnvP;

typedef union {
    jboolean z;
    int i;
    long long j;
    float f;
    double d;
    jobject l;
} jvalue;

struct JavaVMOption {
    char *optionString;
    void *extraInfo;
};

struct JavaVMInitArgs {
    jint version;
    jint nOptions;
    struct JavaVMOption *options;
    jboolean ignoreUnrecognized;
};

/* JNI function table indices. */
#define JNI_FIND_CLASS 6
#define JNI_EXCEPTION_OCCURRED 15
#define JNI_EXCEPTION_DESCRIBE 16
#define JNI_GET_STATIC_METHOD_ID 113
#define JNI_NEW_STRING_UTF 167
#define JNI_NEW_OBJECT_ARRAY 172
#define JNI_SET_OBJECT_ARRAY_ELEMENT 174
#define JNI_CALL_STATIC_VOID_METHOD_A 143

typedef jint (*create_vm_fn)(JavaVM *, JNIEnvP *, void *);
typedef int (*registrar_fn)(JNIEnvP);
typedef void *(*dlsym_fn)(void *, const char *);
typedef void *(*dlopen_fn)(const char *, int);

extern void *dlsym(void *, const char *);
extern void *dlopen(const char *, int);
extern void exit(int);
extern char *getenv(const char *);
extern long write(int, const void *, unsigned long);
extern void *malloc(unsigned long);
extern int strcmp(const char *, const char *);
extern char *strstr(const char *, const char *);
extern unsigned long strlen(const char *);

#define RTLD_NOW 2

/* Generated by build.sh from the bundle's libandroid_runtime.so. */
static const char *kRegistrars[] = {
#include "registrars.inc"
};

static long slen(const char *s) {
    return s ? (long)strlen(s) : 0;
}

/* Both streams, because which of them survives into this call context is not
 * obvious and one of them is enough. Plain write(), which is what the first
 * design used and what demonstrably reached the terminal. */
static void say(const char *s) {
    if (!s) return;
    unsigned long n = (unsigned long)slen(s);
    write(1, s, n);
    write(2, s, n);
}

static void say_dec(long value) {
    char out[24];
    int i = 0;
    unsigned long magnitude;
    if (value < 0) {
        out[i++] = '-';
        magnitude = (unsigned long)(-value);
    } else {
        magnitude = (unsigned long)value;
    }
    char tmp[20];
    int n = 0;
    do {
        tmp[n++] = '0' + (magnitude % 10);
        magnitude /= 10;
    } while (magnitude);
    while (n) out[i++] = tmp[--n];
    write(1, out, (unsigned long)i);
    write(2, out, (unsigned long)i);
}

static void fail(const char *what, const char *detail) {
    say("launcher: ");
    say(what);
    if (detail) {
        say(": ");
        say(detail);
    }
    say("\n");
}

/* Splits a space separated argument list into a String[] through the JNI table. */
static jobjectArray build_args(void *table[], JNIEnvP env, const char *spec) {
    if (!spec || !*spec) return 0;

    /* Count and copy the pieces without allocating: the strings live in the
     * environment, which outlives this. */
    static char buffer[4096];
    static const char *pieces[64];
    long n = 0;
    long len = slen(spec);
    if (len >= (long)sizeof(buffer)) len = (long)sizeof(buffer) - 1;
    for (long i = 0; i < len; i++) buffer[i] = spec[i];
    buffer[len] = 0;

    char *p = buffer;
    while (*p && n < 64) {
        while (*p == ' ') p++;
        if (!*p) break;
        pieces[n++] = p;
        while (*p && *p != ' ') p++;
        if (*p) *p++ = 0;
    }
    if (n == 0) return 0;

    jstring (*new_string_utf)(JNIEnvP, const char *) =
        (jstring(*)(JNIEnvP, const char *))table[JNI_NEW_STRING_UTF];
    jobjectArray (*new_object_array)(JNIEnvP, int, jclass, jobject) =
        (jobjectArray(*)(JNIEnvP, int, jclass, jobject))table[JNI_NEW_OBJECT_ARRAY];
    void (*set_element)(JNIEnvP, jobjectArray, int, jobject) =
        (void(*)(JNIEnvP, jobjectArray, int, jobject))table[JNI_SET_OBJECT_ARRAY_ELEMENT];

    jclass string_class = ((jclass(*)(JNIEnvP, const char *))table[JNI_FIND_CLASS])(
        env, "java/lang/String");
    if (!string_class) return 0;

    jobjectArray array = new_object_array(env, (int)n, string_class, 0);
    if (!array) return 0;
    for (long i = 0; i < n; i++) {
        jstring s = new_string_utf(env, pieces[i]);
        if (s) set_element(env, array, (int)i, s);
    }
    return array;
}

static int run_class(JNIEnvP env, const char *class_name, const char *args_spec);

/* The host binary calls this from its main, which is late enough that the
 * environment exists and early enough to take over before the host's own main
 * body runs. The host is therefore any Bionic binary that creates a VM; its
 * arguments supply the class path and boot class path. */
jint JNI_CreateJavaVM(JavaVM *vm, JNIEnvP *env, void *args) {
    say("launcher: interposed JNI_CreateJavaVM\n");
    static create_vm_fn real_create_vm;
    if (!real_create_vm) {
        real_create_vm = (create_vm_fn)dlsym((void *)-1L, "JNI_CreateJavaVM");
    }
    if (!real_create_vm) {
        fail("cannot find the real JNI_CreateJavaVM", 0);
        exit(2);
    }
    jint created = real_create_vm(vm, env, args);
    if (created != 0 || !env || !*env) {
        say("launcher: the VM did not start: ");
        say_dec(created);
        say("\n");
        exit(2);
    }

    const char *class_name = getenv("MOSAIC_LAUNCH_CLASS");
    const char *runtime_path = getenv("MOSAIC_LAUNCH_RUNTIME");
    const char *args_spec = getenv("MOSAIC_LAUNCH_ARGS");
    if (!class_name || !runtime_path) {
        fail("need MOSAIC_LAUNCH_CLASS and MOSAIC_LAUNCH_RUNTIME", 0);
        exit(2);
    }

    void *runtime = dlopen(runtime_path, RTLD_NOW);
    if (!runtime) {
        fail("cannot open libandroid_runtime", runtime_path);
        exit(2);
    }

    int registered = 0;
    for (unsigned long i = 0; i < sizeof(kRegistrars) / sizeof(kRegistrars[0]); i++) {
        /* libandroid_runtime's handle first, which is where most of them live,
         * then the global scope, which is where the rest do: some registrars are
         * defined in libraries libandroid_runtime merely needs, such as libhwui,
         * which registers android.graphics.Typeface's natives. */
        registrar_fn fn = (registrar_fn)dlsym(runtime, kRegistrars[i]);
        if (!fn) fn = (registrar_fn)dlsym((void *)0 /* RTLD_DEFAULT */, kRegistrars[i]);
        if (!fn) continue;
        int result = fn(*env);
        if (result != 0) {
            say("launcher: ");
            say(kRegistrars[i]);
            say(" returned ");
            say_dec(result);
            say("\n");
        }
        registered++;
    }
    say("launcher: registered ");
    say_dec(registered);
    say(" native registrars\n");

    int status = run_class(*env, class_name, args_spec);
    exit(status);
}

static int run_class(JNIEnvP env, const char *class_name, const char *args_spec) {
    /* FindClass takes a slash separated name. A dotted one works because ART
     * tolerates it and warns, which is not something to rely on. */
    static char slashed[512];
    long i = 0;
    for (; class_name[i] && i < (long)sizeof(slashed) - 1; i++) {
        slashed[i] = class_name[i] == '.' ? '/' : class_name[i];
    }
    slashed[i] = 0;

    void **table = *(void ***)env;

    jclass (*find_class)(JNIEnvP, const char *) =
        (jclass(*)(JNIEnvP, const char *))table[JNI_FIND_CLASS];
    jmethodID (*get_static_method)(JNIEnvP, jclass, const char *, const char *) =
        (jmethodID(*)(JNIEnvP, jclass, const char *, const char *))table[JNI_GET_STATIC_METHOD_ID];
    void (*call_static_void)(JNIEnvP, jclass, jmethodID, jvalue *) =
        (void(*)(JNIEnvP, jclass, jmethodID, jvalue *))table[JNI_CALL_STATIC_VOID_METHOD_A];

    jclass target = find_class(env, slashed);
    if (!target) {
        fail("class not found", class_name);
        return 2;
    }
    jmethodID main_method = get_static_method(env, target, "main", "([Ljava/lang/String;)V");
    if (!main_method) {
        fail("no main(String[])", class_name);
        return 2;
    }

    jvalue argument[1];
    argument[0].l = build_args(table, env, args_spec);

    say("launcher: running ");
    say(class_name);
    say("\n");
    call_static_void(env, target, main_method, argument);

    /* If main threw, the exception is pending on this native frame. Exiting
     * without looking at it hides the only description of what went wrong --
     * an uncaught exception reaches no Java frame to print it. */
    jobject (*exception_occurred)(JNIEnvP) =
        (jobject(*)(JNIEnvP))table[JNI_EXCEPTION_OCCURRED];
    void (*exception_describe)(JNIEnvP) = (void(*)(JNIEnvP))table[JNI_EXCEPTION_DESCRIBE];
    if (exception_occurred(env)) {
        say("launcher: ");
        say(class_name);
        say(" threw, and the exception was pending on the native frame:\n");
        exception_describe(env);
        return 1;
    }
    return 0;
}
