# SPDX-License-Identifier: GPL-3.0-or-later

name: Check Rust Package

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Format check
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Test
        run: cargo test
